name: voila
channels:
  - defaults
  - conda-forge
dependencies:
  - appmode
  - ipyvolume
#  - nbinteract
#  - pip-review
#  - geoplotlib 
  - nbformat
  - voila
  - voila-material
  - voila-gridstack
  - voila-vuetify 
  - voila-reveal 
  - bqplot
  - ipympl
  - ipython
  - ipyvolume
  - pip-review
  - plotly
  - ipywidgets
  - folium
  - scipy
  - pygments 
  - folium
  - numpy 
  - matplotlib 
  - jupyterlab 
  - pandas 
  - squarify 
  - bokeh 
  - geoplotlib 
  - seaborn 
  - pyglet
  - scipy
  - mysql 
  - PyMySQL 
  - ibm_db 
  - mysql-connector-python-rf 
  - weaviate-client
  - bqplot
  - xleaflet
  - xeus-cling